name: Test

# Trigger on pull requests to main and pushes to feature branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  # Test Client (Frontend)
  test-client:
    runs-on: ubuntu-latest
    # Only run if client files have changed
    if: contains(github.event.head_commit.modified, 'client/') || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      # Run tests if they exist
      - name: Run tests
        working-directory: ./client
        run: npm test || echo "No tests configured for client, skipping..."

  # Test Server (Backend)
  test-server:
    runs-on: ubuntu-latest
    # Only run if server files have changed
    if: contains(github.event.head_commit.modified, 'server/') || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      # Run tests if they exist
      - name: Run tests
        working-directory: ./server
        run: npm test || echo "No tests configured for server, skipping..."

  # Lint Client
  lint-client:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'client/') || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Run linting
        working-directory: ./client
        run: npm run lint || echo "No lint script configured for client, skipping..."